### ISSUE TITLE
Missing likes data inside server

### ISSUE THREAD

**Issue by geluso** [learn-co-curriculum/js-quotes-practice#4]
This practice challenge mentions Likes but there's nothing in the JSON data or on the JSON server to support Likes. 

Fix: add Likes property to each quote object. Rewrite API specification to use PUT instead of POST to modify a quote with an updated like.

**Comment by rrcobb** [comment]
was this addressed by https://github.com/learn-co-curriculum/js-quotes-practice/pull/2 ?

**Comment by rrcobb** [comment]
Rereading, it looks like #2 made a deliberate change so that likes were a separate resource.

I think `db.json` has the right thing for the README in both worlds, before that commit (PUT / object property) or after that commit (POST / separate resource)

**Comment by geluso** [comment]
Yeah, whoops, I did not see the likes object at the end of the JSON file. I'm rereading the README file now to triple-verify everything is consistent. Thanks for replying quickly @rrcobb

**Comment by geluso** [comment]
Having the likes as their own resource is fine. There's still a discrepancy in instructions about how they're created and stored.

Use a `POST` request to `http://localhost:3000/quotes/id`

should replace `quotes` in the url with `likes`.

Use a `POST` request to `http://localhost:3000/likes/id`

Also is not the `id` unnecessary? Since we're using `POST` to create a new like we shouldn't specify the `id` of the like in the URL. Instead we should `POST` to just `http://localhost:3000/likes` and JSON server will create an ID for that like once it's created. In fact, using `POST` against `/quotes/id` or `/likes/id` results in a 404 from `json-server`.

#2 refers to inferring the number of likes from the length of an array. Right now there's no way to get a list of likes for each quote. (You can't `POST` to a route with an id to categorize them like this.) We can `GET` all the likes at once and filter or tally all the likes according to their quoteId.

Standing inconsistencies:
* You can not `POST` to a resource route with a `/id`
* It seems like the URL should refer to `/likes` instead of `/quotes`

I still recommend to simply this lab by making Likes a property on each quote object.

**Comment by telegraham** [comment]
@geluso thanks for this catch — you're right, this should be a `POST` to `http://localhost:3000/likes` with a `quoteId` in the body of the object sent from the client. I'll PR this up.

**Comment by telegraham** [comment]
https://github.com/learn-co-curriculum/js-quotes-practice/pull/5
